// shared/lib/constants/piece-types.ts
// Piece types used in the sorting step, in the same order as the laundry's
// paper invoice. Labels live in i18n under "piece_types".
export const PIECE_TYPE_KEYS = [
  "jacket",
  "pakistani_suit",
  "ladies_dress",
  "skirt",
  "blouse",
  "abaya",
  "tarha",
  "coat",
  "over_coat",
  "besht",
  "tie",
  "bed_sheet",
  "bed_spread",
  "pillow_cover",
  "blanket",
  "curtain",
  "carpet",
  "shoes",
  "thob",
  "sleep_shirt",
  "wool_thob",
  "ghutra",
  "shomagh",
  "hat",
  "serwal_long",
  "serwal_short",
  "under_shirt",
  "t_shirt",
  "shirt",
  "pajama",
  "pajama_trousers",
  "pants",
  "police_suit",
  "medical_suit",
  "socks",
  "towel",
  "school_dress",
] as const;

export type PieceTypeKey = (typeof PIECE_TYPE_KEYS)[number];
